auction:
  max-listings-per-player: 10
  duration: 86400
  commission-fee: 5.0

nightshop:
  timezone: "Asia/Ho_Chi_Minh"
  open-time: 20
  close-time: 22
  announce-open: true
  announce-close: true

sounds:
  enabled: true

language:
  file: "language.yml"

placeholderapi:
  enabled: true

debug: false